# Generated by Django 4.2.9 on 2024-01-25 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('additional_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('time_multiplier_factor', models.FloatField()),
                ('waiting_charge', models.DecimalField(decimal_places=2, max_digits=5)),
                ('distance_limit', models.DecimalField(decimal_places=2, max_digits=5)),
                ('day_of_week', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_traveled', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ride_time', models.DurationField()),
                ('wait_time', models.DurationField()),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('pricing_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.pricingconfig')),
            ],
        ),
    ]
